dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - python3 -m pip install pipx
  - pipx install poetry==1.6.1
  - poetry install --with numpy,test

script:
  - poetry run coverage run -m unittest tests
  - poetry run flake8 forcedimension_core --ignore "F401,E501"
  - poetry run coveralls
