dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - python3 -m pip install pipenv
  - python3 -m pipenv install

script:
  - python3 -m pipenv run python3 -m unittest tests
