[tool.poetry]
name = "forcedimension-core"
version = "1.0.0rc1"
description = "Unofficial Python Bindings for the Force Dimension SDK"
authors = ["Ember Chow <emberchow.business@gmail.com>"]
readme = "README.md"
license = "LGPL-3.0-or-later"
documentation = "https://force-dimension-core-python-documentation.readthedocs.io/en/latest/index.html"
repository = "https://github.com/EmDash00/forcedimension_core-python"
classifiers = [
    "Python :: Implementation :: CPython",
    "Python :: Implementation :: PyPy",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
pydantic = "^2"
typing-extensions = "^4.6.0"

numpy = [
  { version = "^1.20.0", python = "<3.12", optional=true },
  { version = "^1.26.0", python = ">=3.12,<3.13", optional=true },
]

[tool.poetry.extras]
numpy = ['numpy']

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^6.2.1"
sphinx-rtd-theme = "^1.3.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coverage = { version = "^7.0.2", extras = ["toml"] }
flake8 = [
  { version = "^5.0.0", python = "<3.8.1" },
  { version = "^6.0.0", python = ">=3.8.1" },
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
omit = [
  "tests",
]

[tool.coverage.report]
omit = [
  "tests/*",
  "forcedimension_core/typing.py"
]
exclude_lines = [ "\\.\\.\\." ]
