[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "forcedimension_core"
version = "1.0.0"
authors = [
    { name="Ember Chow", email="emberchow.business@gmail.com" },
]
description = "Python Bindings for the ForceDimension SDK"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pydantic~=2", "typing_extensions~=4.6.2"]
license = {file="LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

[project.optional-dependencies]
all = []
numpy = [
  "numpy~=1.20.3"
]

[project.urls]
"Homepage" = "https://github.com/EmDash00/forcedimension_core-python"

[tool.coverage.run]
branch = true
omit = [
  "tests",
]

[tool.coverage.report]
omit = [
  "tests/*",
  "forcedimension_core/typing.py"
]
exclude_lines = [ "\\.\\.\\." ]
