[tool.poetry]
name = "forcedimension-core"
version = "1.0.0rc1"
description = "Unofficial Python Bindings for the Force Dimension SDK"
authors = ["Ember Chow <emberchow.business@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"
documentation = "https://force-dimension-core-python-documentation.readthedocs.io/en/latest/index.html"
repository = "https://github.com/EmDash00/forcedimension_core-python"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
pydantic = "^2"
typing-extensions = "^4.6.0"

[tool.poetry.group.numpy]
optional = true

[tool.poetry.group.numpy.dependencies]
numpy = [
  { version = "^1.20.0", python = "<3.12" },
  { version = "^1.26.0", python = ">=3.12,<3.13" },
]

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^6.2.1"
sphinx-rtd-theme = "^1.3.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coveralls = "~3.3.1"
coverage = {version = "*", extras = ["toml"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
omit = [
  "tests",
]

[tool.coverage.report]
omit = [
  "tests/*",
  "forcedimension_core/typing.py"
]
exclude_lines = [ "\\.\\.\\." ]
